---
driver:
  name: ec2
  aws_ssh_key_id: aws
  security_group_ids: ["sg-f2378b87"]
  region: us-east-1
  availability_zone: a
  require_chef_omnibus: true
  instance_type: t2.micro
  associate_public_ip: true
  shared_credentials_profile: default
  subnet_id: subnet-d343dab7

transport:
  ssh_key: /root/.ec2/aws
  username: ec2-user

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2
    driver:
      image_id: ami-55ef662f
suites:
  - name: default
    run_list:
      - recipe[jenkins-chef-pipeline::default]
    attributes:
